// Author https://github.com/yegor-sytnyk/movies-list

export default [
  {
    id: 1,
    uid: "hfjafjak2",
    name: "Beetlejuice",
    email: "beet@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-1.jpg",
  },
  {
    id: 2,
    uid: "hfjafj2k2",
    name: "Rina",
    email: "rina@gmail.com",
    last_login: "11-12-2023",
    role: "sales",
    image: "messages-2.jpg",
  },
  {
    id: 3,
    uid: "hfjaf12ak2",
    name: "ciko ",
    email: "ciko@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-1.jpg",
  },
  {
    id: 4,
    uid: "sadhf12",
    name: "ciko",
    email: "ciko@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-2.jpg",
  },
  {
    id: 5,
    uid: "yuadsf",
    name: "Beto",
    email: "beto@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "team-2.jpg",
  },
  {
    id: 6,
    uid: "923jasf",
    name: "rian",
    email: "joko12prasetio@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "team-1.jpg",
  },
  {
    id: 7,
    uid: "u123asfj",
    name: "Jamal",
    email: "hosealeonardo12@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-1.jpg",
  },
  {
    id: 8,
    uid: "hjadsfaf",
    name: "ranto iniguana jamal",
    email: "jamaludinhebat@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-1.jpg",
  },
  {
    id: 9,
    uid: "hafnafmafa",
    name: "siska erika jamal",
    email: "siskaerikajamal@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-1.jpg",
  },
  {
    id: 10,
    uid: "ashjfandam",
    name: "rianto",
    email: "ahmedbeatrianto@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-2.jpg",
  },
  {
    id: 11,
    uid: "jakfakfna",
    name: "rianto aso jamal",
    email: "riantojamalgantengbanget@gmail.com",
    last_login: "14-10-2023",
    role: "sales",
    image: "messages-1.jpg",
  },
];
