import React from "react";

const Timeline = ({jenisKerjasama}) => {
  return (
    <div>
      <table className="table table-sm caption-top">
        <caption className="fw-bold fs-5">Timeline</caption>
        <thead className="table-primary">
          <tr>
            <th scope="col">Process</th>
            <th scope="col">1</th>
            <th scope="col">2</th>
            <th scope="col">3</th>
            <th scope="col">4</th>
            <th scope="col">5</th>
            <th scope="col">6</th>
            <th scope="col">7</th>
            <th scope="col">8</th>
            <th scope="col">9</th>
            <th scope="col">10</th>
            <th scope="col">11</th>
            <th scope="col">12</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>New HD</td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
          </tr>
          <tr>
            <td>Renovasi</td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
          </tr>
          <tr>
            <td>Kirim Mesin</td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
          </tr>
          <tr>
            <td>Install Mesin</td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
          </tr>
          <tr>
            <td>Izin HD & BPJS</td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
          </tr>
          <tr>
            <td>Training</td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
          </tr>
          <tr>
            <td>1t Running Patient</td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
            <td>
              <input
                type="checkbox"
                name=""
                id=""
                className="form-check-input"
              />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default Timeline;
