export default [
  {
    id: 1,
    uid: "asjfaksd",
    name_deals: "Rujukan PCR Rs. Siti Aisyah",
    Stage: "Leads",
    jumlah: "0",
    name_owner: "Raima",
    approval_status: "succes",
    created_at: "12-09-2023",
    updated_at: "12-11-2023",
  },
  {
    id: 2,
    uid: "jsakfda",
    name_deals: "Rujukan PT.SkyJok",
    Stage: "Leads",
    jumlah: "0",
    name_owner: "Sintia",
    approval_status: "succes",
    created_at: "12-08-2023",
    updated_at: "12-12-2023",
  },
  {
    id: 3,
    uid: "jjancsfs",
    name_deals: "Rujukan PT.SanKrin",
    Stage: "Leads",
    jumlah: "0",
    name_owner: "Rahmet",
    approval_status: "succes",
    created_at: "12-07-2023",
    updated_at: "12-11-2023",
  },
];
